version: '3.7'

services:
  duplicati:
    image: linuxserver/duplicati:v2.0.5.1-2.0.5.1_beta_2020-01-18-ls68
    container_name: duplicati
    networks:
      - web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - config:/config
      - backups:/backups
      - source:/source

      - nextcloud_data:/source/nextcloud/data:ro
      - nextcloud_config:/source/nextcloud/config:ro
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.duplicati.loadbalancer.server.port=8200

      # HTTPS
      - traefik.http.routers.duplicati.rule=Host(`duplicati.noizwaves.cloud`)
      - traefik.http.routers.duplicati.tls.certresolver=mytlschallenge
      - traefik.http.routers.duplicati.entrypoints=web-secured
      - traefik.http.routers.duplicati.tls=true
      - traefik.http.routers.duplicati.service=duplicati

      # protect with Authelia
      - traefik.http.routers.duplicati.middlewares=authelia@docker

volumes:
  config:
    driver: local

  backups:
    driver: local

  source:
    driver: local

  # Nextcloud source data to back up
  nextcloud_data:
    external: true
  nextcloud_config:
    external: true

networks:
  web:
    external: true